[package]
name = "sonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
hyper = { version = "0.14.27", features = ["full"] }
tokio = {version = "1.33.0", features = ["full"] }
